//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1270.0 using the following command:
// xscgen C:\Users\kammchan\Downloads\myKafkaXSD.xml -n KafkaXmlConsumer.Models -o Models
namespace KafkaXmlConsumer.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("HeaderType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HeaderType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Action")]
        public string Action { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("ApplicationSource")]
        public string ApplicationSource { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("CRTVersionNumber")]
        public string CrtVersionNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("ModeType")]
        public string ModeType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("RootType")]
        public string RootType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Timestamp")]
        public string Timestamp { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BodyType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BodyType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CpyType> _cpy;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPY")]
        public System.Collections.ObjectModel.Collection<CpyType> Cpy
        {
            get
            {
                return _cpy;
            }
            private set
            {
                _cpy = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BodyType" /> class.</para>
        /// </summary>
        public BodyType()
        {
            this._cpy = new System.Collections.ObjectModel.Collection<CpyType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPYIdentification")]
        public CpyIdentificationType CpyIdentification { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPYRoles")]
        public CpyRolesType CpyRoles { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPYCharacteristics")]
        public CpyCharacteristicsType CpyCharacteristics { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Adress")]
        public AdressType Adress { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPYInternalRatings")]
        public CpyInternalRatingsType CpyInternalRatings { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPYLifeCycle")]
        public CpyLifeCycleType CpyLifeCycle { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPYLinks")]
        public CpyLinksType CpyLinks { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPYTradeData")]
        public CpyTradeDataType CpyTradeData { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPYCasaData")]
        public CpyCasaDataType CpyCasaData { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("DFAClassification")]
        public DfaClassificationType DfaClassification { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("EMIRClassification")]
        public EmirClassificationType EmirClassification { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("MifidData")]
        public MifidDataType MifidData { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("KYCData")]
        public KycDataType KycData { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Nydata")]
        public NydataType Nydata { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CpyLocalIdentificationType> _cpyLocalIdentification;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CPYLocalIdentification")]
        public System.Collections.ObjectModel.Collection<CpyLocalIdentificationType> CpyLocalIdentification
        {
            get
            {
                return _cpyLocalIdentification;
            }
            private set
            {
                _cpyLocalIdentification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CpyType" /> class.</para>
        /// </summary>
        public CpyType()
        {
            this._cpyLocalIdentification = new System.Collections.ObjectModel.Collection<CpyLocalIdentificationType>();
            this._externalId = new System.Collections.ObjectModel.Collection<ExternalIdType>();
            this._cpyChilds = new System.Collections.ObjectModel.Collection<ScType>();
            this._additionalFields = new System.Collections.ObjectModel.Collection<AdditionalFieldType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ExternalIdType> _externalId;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ExternalId")]
        public System.Collections.ObjectModel.Collection<ExternalIdType> ExternalId
        {
            get
            {
                return _externalId;
            }
            private set
            {
                _externalId = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ScType> _cpyChilds;
        
        [System.Xml.Serialization.XmlArrayAttribute("CPYChilds")]
        [System.Xml.Serialization.XmlArrayItemAttribute("SC")]
        public System.Collections.ObjectModel.Collection<ScType> CpyChilds
        {
            get
            {
                return _cpyChilds;
            }
            private set
            {
                _cpyChilds = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CpyChilds collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CpyChildsSpecified
        {
            get
            {
                return (this.CpyChilds.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AdditionalFieldType> _additionalFields;
        
        [System.Xml.Serialization.XmlArrayAttribute("AdditionalFields")]
        [System.Xml.Serialization.XmlArrayItemAttribute("AdditionalField")]
        public System.Collections.ObjectModel.Collection<AdditionalFieldType> AdditionalFields
        {
            get
            {
                return _additionalFields;
            }
            private set
            {
                _additionalFields = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the AdditionalFields collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdditionalFieldsSpecified
        {
            get
            {
                return (this.AdditionalFields.Count != 0);
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ISOAddress")]
        public IsoAddressType IsoAddress { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYIdentificationType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyIdentificationType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Legal")]
        public LegalType Legal { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Person")]
        public PersonType Person { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LegalType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LegalType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("ClassOfLegalEntity")]
        public string ClassOfLegalEntity { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("INSEELegalName")]
        public string InseeLegalName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("LongName")]
        public string LongName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NormalizedLegalName")]
        public string NormalizedLegalName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ShortName")]
        public string ShortName { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PersonType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PersonType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("BirthDate")]
        public string BirthDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BirthPlace")]
        public string BirthPlace { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FirstName")]
        public string FirstName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("LastName")]
        public string LastName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("MaritalStatus")]
        public string MaritalStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Sex")]
        public string Sex { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYRolesType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyRolesType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("CalyonPrimaryCoverageUnit")]
        public string CalyonPrimaryCoverageUnit { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ESFWorldwidePilotEntity")]
        public string EsfWorldwidePilotEntity { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ForcedCalyonPrimaryCoverageUnit")]
        public string ForcedCalyonPrimaryCoverageUnit { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FraneRunEntity")]
        public string FraneRunEntity { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FraneRunManager")]
        public string FraneRunManager { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PilotDivision")]
        public string PilotDivision { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("RMCCalyon")]
        public string RmcCalyon { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ReportingEntity")]
        public string ReportingEntity { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("UEWorldwidePilotEntity")]
        public string UeWorldwidePilotEntity { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYCharacteristicsType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyCharacteristicsType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("BAFIAccountingCode")]
        public string BafiAccountingCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BaselPortfolio")]
        public string BaselPortfolio { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CalyonRelationType")]
        public string CalyonRelationType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CalyonRelationTypeReviewDate", DataType="date")]
        public System.DateTime CalyonRelationTypeReviewDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CalyonRelationTypeReviewDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CalyonRelationTypeReviewDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Category")]
        public string Category { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CategoryValidationDate")]
        public string CategoryValidationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CategoryValidationStatus")]
        public string CategoryValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ControlCountry")]
        public string ControlCountry { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ControlCountryValidationDate")]
        public string ControlCountryValidationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ControlCountryValidationStatus")]
        public string ControlCountryValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("KiwisRelationType")]
        public string KiwisRelationType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("KiwisRelationTypeReviewDate", DataType="date")]
        public System.DateTime KiwisRelationTypeReviewDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the KiwisRelationTypeReviewDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KiwisRelationTypeReviewDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NAFActivityCode")]
        public string NafActivityCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NAFActivityCodeRev2")]
        public string NafActivityCodeRev2 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NationalityCountry")]
        public string NationalityCountry { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NationalityCountryValidationDate")]
        public string NationalityCountryValidationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NationalityCountryValidationStatus")]
        public string NationalityCountryValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PrincipalBusinessArea")]
        public string PrincipalBusinessArea { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PrincipalBusinessAreaValidationDate")]
        public string PrincipalBusinessAreaValidationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PrincipalBusinessAreaValidationStatus")]
        public string PrincipalBusinessAreaValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PublicPrivateCode")]
        public string PublicPrivateCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ResidenceCountry")]
        public string ResidenceCountry { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ResidenceCountryValidationDate")]
        public string ResidenceCountryValidationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ResidenceCountryValidationStatus")]
        public string ResidenceCountryValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("RiskCountry")]
        public string RiskCountry { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NAFActivityCodeRev2INSEE")]
        public string NafActivityCodeRev2Insee { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NationalityCountryFS")]
        public string NationalityCountryFs { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NationalityCountryFSValidationStatus")]
        public string NationalityCountryFsValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NationalityCountryFSValidationDate")]
        public string NationalityCountryFsValidationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ResidenceCountryFS")]
        public string ResidenceCountryFs { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ResidenceCountryFSValidationStatus")]
        public string ResidenceCountryFsValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ResidenceCountryFSValidationDate")]
        public string ResidenceCountryFsValidationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CategoryFS")]
        public string CategoryFs { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CategoryFSValidationStatus")]
        public string CategoryFsValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CategoryFSValidationDate")]
        public string CategoryFsValidationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PrincipalBusinessAreaFS")]
        public string PrincipalBusinessAreaFs { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PrincipalBusinessAreaFSValidationStatus")]
        public string PrincipalBusinessAreaFsValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PrincipalBusinessAreaFSValidationDate")]
        public string PrincipalBusinessAreaFsValidationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ControlCountryFS")]
        public string ControlCountryFs { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ControlCountryFSValidationStatus")]
        public string ControlCountryFsValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ControlCountryFSValidationDate")]
        public string ControlCountryFsValidationDate { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AdressType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdressType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("City")]
        public string City { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Line1")]
        public string Line1 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Line2")]
        public string Line2 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("State")]
        public string State { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ZipCode")]
        public string ZipCode { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYInternalRatingsType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyInternalRatingsType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("Date", DataType="date")]
        public System.DateTime Date { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Date property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FinalInternalRating")]
        public string FinalInternalRating { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Methodology")]
        public string Methodology { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Reason")]
        public string Reason { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYLifeCycleType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyLifeCycleType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("CreationDate", DataType="date")]
        public System.DateTime CreationDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CreationDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreationDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("InCreationFlag")]
        public string InCreationFlag { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("KiwisRelationShipCode")]
        public string KiwisRelationShipCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("KiwisRelationShipCodeReviewDate", DataType="date")]
        public System.DateTime KiwisRelationShipCodeReviewDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the KiwisRelationShipCodeReviewDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KiwisRelationShipCodeReviewDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ModificationDate", DataType="date")]
        public System.DateTime ModificationDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ModificationDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModificationDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ModifiedBy")]
        public string ModifiedBy { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("RelationShipCode")]
        public string RelationShipCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("RelationShipCodeReviewDate", DataType="date")]
        public System.DateTime RelationShipCodeReviewDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RelationShipCodeReviewDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelationShipCodeReviewDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("UpdateDate", DataType="date")]
        public System.DateTime UpdateDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UpdateDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdateDateSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYLinksType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyLinksType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("GroupLinkDate", DataType="date")]
        public System.DateTime GroupLinkDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the GroupLinkDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GroupLinkDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ParentCPHid")]
        public string ParentCpHid { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ParentCPHlongName")]
        public string ParentCpHlongName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ParentId")]
        public string ParentId { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ProposedParentCPH")]
        public string ProposedParentCph { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("SubsidiaryParent")]
        public string SubsidiaryParent { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CPMBranchFlag")]
        public string CpmBranchFlag { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYTradeDataType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyTradeDataType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("DealingRestriction")]
        public string DealingRestriction { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("DealingRestrictionReviewDate", DataType="date")]
        public System.DateTime DealingRestrictionReviewDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DealingRestrictionReviewDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DealingRestrictionReviewDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Depository")]
        public string Depository { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FiduciaryRole")]
        public string FiduciaryRole { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FiduciaryRoleType")]
        public string FiduciaryRoleType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FundOriginator")]
        public string FundOriginator { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PrincipalSponsor")]
        public string PrincipalSponsor { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("RegroupingCPY")]
        public string RegroupingCpy { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("SponsorType")]
        public string SponsorType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("DNDRequestor")]
        public string DndRequestor { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYCasaDataType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyCasaDataType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("CAConsoId")]
        public string CaConsoId { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("EconomicAgentCode")]
        public string EconomicAgentCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("GroupCreditAgricoleFlag")]
        public string GroupCreditAgricoleFlag { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DFAClassificationType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DfaClassificationType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("Commo")]
        public string Commo { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Credits")]
        public string Credits { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Entity")]
        public string Entity { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Equity")]
        public string Equity { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("FX")]
        public string Fx { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Rates")]
        public string Rates { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ClientClassification15a6")]
        public string ClientClassification15A6 { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EMIRClassificationType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmirClassificationType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("Emirclassification")]
        public string Emirclassification { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MifidDataType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MifidDataType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("ClientClassificationFlag")]
        public string ClientClassificationFlag { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("InitialNotificationDate", DataType="date")]
        public System.DateTime InitialNotificationDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the InitialNotificationDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InitialNotificationDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("InitialNotificationStatus")]
        public string InitialNotificationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("InternalSuitabilityRating")]
        public string InternalSuitabilityRating { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("LawClassificationFlag")]
        public string LawClassificationFlag { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("VanilleProductExperience")]
        public string VanilleProductExperience { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KYCDataType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KycDataType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("KYCRating")]
        public string KycRating { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("KYCStatus")]
        public string KycStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("KYCValidationDate", DataType="date")]
        public System.DateTime KycValidationDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the KycValidationDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KycValidationDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("WorldwideKYCId")]
        public string WorldwideKycId { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NydataType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NydataType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("NYlocalKactusStatus")]
        public string NYlocalKactusStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("NYlocalRelationShipCode")]
        public string NYlocalRelationShipCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("OFAC")]
        public string Ofac { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PatriotAct")]
        public string PatriotAct { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PatriotActCertificationDate")]
        public string PatriotActCertificationDate { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("UsCompliant")]
        public string UsCompliant { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYLocalIdentificationType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyLocalIdentificationType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("AliasId")]
        public string AliasId { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("AliasType")]
        public string AliasType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("KYCValidationStatus")]
        public string KycValidationStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("LocalRelationShipCode")]
        public string LocalRelationShipCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("LocalRelationType")]
        public string LocalRelationType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("RR")]
        public string Rr { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExternalIdType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExternalIdType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("ExternalAliasId")]
        public string ExternalAliasId { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ExternalAliasType")]
        public string ExternalAliasType { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CPYChildsType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CpyChildsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ScType> _sc;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SC")]
        public System.Collections.ObjectModel.Collection<ScType> Sc
        {
            get
            {
                return _sc;
            }
            private set
            {
                _sc = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CpyChildsType" /> class.</para>
        /// </summary>
        public CpyChildsType()
        {
            this._sc = new System.Collections.ObjectModel.Collection<ScType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SCType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SCIdentification")]
        public ScIdentificationType ScIdentification { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SCRoles")]
        public ScRolesType ScRoles { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Adress")]
        public AdressType Adress { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SCLifeCycle")]
        public ScLifeCycleType ScLifeCycle { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ScLocalIdentificationType> _scLocalIdentification;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("SCLocalIdentification")]
        public System.Collections.ObjectModel.Collection<ScLocalIdentificationType> ScLocalIdentification
        {
            get
            {
                return _scLocalIdentification;
            }
            private set
            {
                _scLocalIdentification = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ScType" /> class.</para>
        /// </summary>
        public ScType()
        {
            this._scLocalIdentification = new System.Collections.ObjectModel.Collection<ScLocalIdentificationType>();
            this._externalId = new System.Collections.ObjectModel.Collection<ExternalIdType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ExternalIdType> _externalId;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ExternalId")]
        public System.Collections.ObjectModel.Collection<ExternalIdType> ExternalId
        {
            get
            {
                return _externalId;
            }
            private set
            {
                _externalId = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("ISOAddress")]
        public IsoAddressType IsoAddress { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Id")]
        public string Id { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SCIdentificationType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScIdentificationType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("CalyonGroupSCFlag")]
        public string CalyonGroupScFlag { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Country")]
        public string Country { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("LongName")]
        public string LongName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ProfitCenter")]
        public string ProfitCenter { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("SCType")]
        public string ScType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("SCinternalType")]
        public string SCinternalType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ShortName")]
        public string ShortName { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SCRolesType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScRolesType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("ReportingEntity")]
        public string ReportingEntity { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ResponsibilityCenter")]
        public string ResponsibilityCenter { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SCLifeCycleType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScLifeCycleType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("CentralStatusCode")]
        public string CentralStatusCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("CreationDate", DataType="date")]
        public System.DateTime CreationDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CreationDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreationDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ModificationDate", DataType="date")]
        public System.DateTime ModificationDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ModificationDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModificationDateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ModifiedBy")]
        public string ModifiedBy { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("UpdateDate", DataType="date")]
        public System.DateTime UpdateDate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the UpdateDate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UpdateDateSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SCLocalIdentificationType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ScLocalIdentificationType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("AliasId")]
        public string AliasId { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("AliasType")]
        public string AliasType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("LocalParentId")]
        public string LocalParentId { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("LocalStatusCode")]
        public string LocalStatusCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("OperationsManager")]
        public string OperationsManager { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ISOAddressType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsoAddressType
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("Department")]
        public string Department { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("SubDepartment")]
        public string SubDepartment { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("BuildingName")]
        public string BuildingName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Floor")]
        public string Floor { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("Room")]
        public string Room { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("StreetName")]
        public string StreetName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("StreetNumber")]
        public string StreetNumber { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("PostBox")]
        public string PostBox { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("RepetitionIndex")]
        public string RepetitionIndex { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TrackType")]
        public string TrackType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("City")]
        public string City { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ZipCode")]
        public string ZipCode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("TownLocName")]
        public string TownLocName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("DistrictName")]
        public string DistrictName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("State")]
        public string State { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AdditionalFieldsType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdditionalFieldsType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AdditionalFieldType> _additionalField;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("AdditionalField")]
        public System.Collections.ObjectModel.Collection<AdditionalFieldType> AdditionalField
        {
            get
            {
                return _additionalField;
            }
            private set
            {
                _additionalField = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AdditionalFieldsType" /> class.</para>
        /// </summary>
        public AdditionalFieldsType()
        {
            this._additionalField = new System.Collections.ObjectModel.Collection<AdditionalFieldType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AdditionalFieldType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AdditionalFieldType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CompositionType> _composition;
        
        [System.Xml.Serialization.XmlElementAttribute("Composition")]
        public System.Collections.ObjectModel.Collection<CompositionType> Composition
        {
            get
            {
                return _composition;
            }
            private set
            {
                _composition = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Composition collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CompositionSpecified
        {
            get
            {
                return (this.Composition.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AdditionalFieldType" /> class.</para>
        /// </summary>
        public AdditionalFieldType()
        {
            this._composition = new System.Collections.ObjectModel.Collection<CompositionType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("code")]
        public string Code { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CompositionType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompositionType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<FieldType> _field;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Field")]
        public System.Collections.ObjectModel.Collection<FieldType> Field
        {
            get
            {
                return _field;
            }
            private set
            {
                _field = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CompositionType" /> class.</para>
        /// </summary>
        public CompositionType()
        {
            this._field = new System.Collections.ObjectModel.Collection<FieldType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FieldType", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FieldType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("code")]
        public string Code { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1270.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CRT", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CRT", Namespace="")]
    public partial class Crt
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Header")]
        public HeaderType Header { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CpyType> _body;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlArrayAttribute("Body")]
        [System.Xml.Serialization.XmlArrayItemAttribute("CPY")]
        public System.Collections.ObjectModel.Collection<CpyType> Body
        {
            get
            {
                return _body;
            }
            private set
            {
                _body = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Crt" /> class.</para>
        /// </summary>
        public Crt()
        {
            this._body = new System.Collections.ObjectModel.Collection<CpyType>();
        }
    }
}
